package origin

// caddyfile.go — deterministic Caddyfile generation (design §2.3).
//
// The generated bytes are PINNED by golden files and by the real
// binary: CI's "Pinned Caddy gate" runs `caddy validate --config` on
// every golden (the pinned v2.11.4 is the authority, exactly like the
// T3 xray gate is for the Germany config).
//
// The layout is fixed and tab-indented (Caddyfile convention), with
// the managed marker as the first line (T7 idempotence keys off it)
// and a trailing newline. NO timestamps, NO map iteration: the render
// is byte-identical across runs for a given Plan.
//
// WS forwarding is NATIVE to Caddy (verified at the pinned tag:
// reverseproxy re-injects Upgrade/Connection to the backend, preserves
// the client Host, and adds X-Forwarded-* — equivalent to the legacy
// nginx snippet, design §1). The ONLY transport tuning emitted is the
// per-OPERATION read/write timeout (nginx proxy_read/send_timeout
// equivalent, idle-safe for long-lived carriers). `stream_timeout`
// (a TOTAL-time cap) is NEVER emitted (decision D7): it would kill a
// long-lived carrier.

import (
	"fmt"
	"strconv"
	"strings"
)

// managedMarker is the first line of every generated Caddyfile.
// T7 idempotence and the installer's "managed by us" detection key off
// this exact string.
const managedMarker = "# Managed by split-tunnel installer - do not edit by hand"

// wsIdleTimeout is the per-operation read/write deadline on the backend
// TCP connection (Caddy's transport http read_timeout/write_timeout).
// It is the nginx proxy_read_timeout 3600s equivalent: an IDLE deadline
// between successive operations, NOT a cap on total connection time —
// a long-lived idle carrier survives, a dead peer is cut after 1h.
const wsIdleTimeout = "3600s"

// RenderCaddyfile renders the Caddyfile for the given Plan.
//   - caddy mode: site block for the domain with reverse_proxy /upload
//     to the loopback WS listener + (challenge/email) tls directive.
//   - cdn mode A (tlsOrigin): the same body but the site block is
//     "<domain>:<originPort>" with `tls internal` (the CDN talks to
//     the origin over TLS; the cert is Caddy-internal).
//   - cdn mode B (plainOrigin) and none mode: ErrNoCaddyfile.
//
// The render is pure (no I/O) and deterministic: the same Plan always
// yields the same bytes.
func RenderCaddyfile(plan Plan) ([]byte, error) {
	if err := plan.validate(); err != nil {
		return nil, err
	}
	switch plan.Mode {
	case ModeCaddy:
		return renderCaddy(plan), nil
	case ModeCDN:
		if plan.CDNSecurity != CDNTLSOrigin {
			return nil, fmt.Errorf("%w: cdn plainOrigin (mode B) needs no Caddy", ErrNoCaddyfile)
		}
		return renderCDNInternal(plan), nil
	default: // ModeNone
		return nil, fmt.Errorf("%w: none mode needs no Caddy", ErrNoCaddyfile)
	}
}

// renderCaddy renders the public ACME site block:
//
//	# Managed by split-tunnel installer - do not edit by hand
//	<domain> {
//		[tls <email>]                          (http01 + email)
//		[tls { issuer acme { [email]; \n\t\t\t   (tlsalpn01,
//		 disable_http_challenge } }]              with/without email)
//		reverse_proxy /upload <upstream> {
//			transport http {
//				read_timeout 3600s
//				write_timeout 3600s
//			}
//		}
//	}
//
// All shapes were validated with the pinned binary (design §2.3,
// T4-C1 email probes).
func renderCaddy(plan Plan) []byte {
	var b strings.Builder
	b.WriteString(managedMarker + "\n")
	b.WriteString(plan.Domain + " {\n")
	switch plan.ACMEChallenge {
	case "", ACMEHTTP01:
		if plan.ACMEEmail != "" {
			b.WriteString("\ttls " + plan.ACMEEmail + "\n")
		}
		// No tls directive = Caddy's default: public ACME via
		// HTTP-01 (verified: apps.tls={} + listen [":443"]).
	case ACMETLSALPN01:
		b.WriteString("\ttls {\n")
		b.WriteString("\t\tissuer acme {\n")
		if plan.ACMEEmail != "" {
			b.WriteString("\t\t\temail " + plan.ACMEEmail + "\n")
		}
		b.WriteString("\t\t\tdisable_http_challenge\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
	default:
		// Unreachable: validate() rejects unknown challenges.
		b.WriteString("\ttls {\n\t\tissuer acme {\n\t\t\tdisable_http_challenge\n\t\t}\n\t}\n")
	}
	b.WriteString("\t" + reverseProxyBlock(plan.UpstreamAddr) + "\n")
	b.WriteString("}\n")
	return []byte(b.String())
}

// renderCDNInternal renders the CDN TLS-origin (mode A) site block:
// the same body as caddy mode, but the site is bound to
// "<domain>:<originPort>" and the TLS is `tls internal` (Caddy's
// private issuer — no public CA, the CDN supplies the public cert;
// verified: listens ONLY on the origin port, host matcher is the bare
// domain so a CDN sending Host: <domain> matches).
func renderCDNInternal(plan Plan) []byte {
	port := plan.OriginPort
	if port == 0 {
		port = 443
	}
	var b strings.Builder
	b.WriteString(managedMarker + "\n")
	b.WriteString(plan.Domain + ":" + strconv.Itoa(port) + " {\n")
	b.WriteString("\ttls internal\n")
	b.WriteString("\t" + reverseProxyBlock(plan.UpstreamAddr) + "\n")
	b.WriteString("}\n")
	return []byte(b.String())
}

// reverseProxyBlock is the shared proxy body (tab-prefixed for site
// blocks). The timeouts are the per-operation idle deadlines (D7);
// `stream_timeout` is deliberately absent (it is a total-time cap and
// would kill long-lived carriers).
func reverseProxyBlock(upstream string) string {
	var b strings.Builder
	b.WriteString("reverse_proxy " + UpstreamPath + " " + upstream + " {\n")
	b.WriteString("\t\ttransport http {\n")
	b.WriteString("\t\t\tread_timeout " + wsIdleTimeout + "\n")
	b.WriteString("\t\t\twrite_timeout " + wsIdleTimeout + "\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}")
	return b.String()
}
